### ISSUE TITLE
高并发商品秒杀系统 | LeDao的博客

### ISSUE THREAD

**Issue by a6678696** [a6678696/a6678696.github.io#508]
https://blog.zoutl.cn/492.html 

 项目地址GitHub地址后端代码 a6678696/MiaoSha: 高并发商品秒杀系统后端代码（前后端分离项目） (github.com) 前端代码 a6678696/miaosha-web: 高并发商品秒杀系统前端代码（前后端分离项目） (github.com) 使用的技术本项目为前后端分离项目，使用到的技术如下：    技术 说明    Spring Boot 后端项目框架   Mybati

**Comment by ytc0418** [comment]
大佬，这个错是怎么回事
2022-04-20 18:01:35.200 ERROR 15720 --- [ntContainer#0-1] o.s.a.r.l.SimpleMessageListenerContainer : Failed to check/redeclare auto-delete queue(s).

org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection timed out: connect
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:61) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:524) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:751) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:214) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2089) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2062) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2042) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueInfo(RabbitAdmin.java:407) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:391) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.attemptDeclarations(AbstractMessageListenerContainer.java:1842) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.redeclareElementsIfNecessary(AbstractMessageListenerContainer.java:1823) ~[spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1349) [spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1195) [spring-rabbit-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_311]
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_311]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81) ~[na:1.8.0_311]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[na:1.8.0_311]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[na:1.8.0_311]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[na:1.8.0_311]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162) ~[na:1.8.0_311]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[na:1.8.0_311]
	at java.net.Socket.connect(Socket.java:606) ~[na:1.8.0_311]

**Comment by a6678696** [comment]
> @ytc0418
> 大佬，这个错是怎么回事

安装RabbitMQ了吗，你使用的后端代码是单体架构还是微服务架构的？

**Comment by pchSir** [comment]
你好，请问这个怎么解决超发的问题呢? 秒杀成功之后进入队列,但是队列是异步的,我没有看到进入队列之后处理数据库库存方法(我思路应该是秒杀成功后进入队列,然后MQ异步支付,库存-1)；我没有看到这部分操作,MQ的异步操作数据库会不会产生与前面秒杀成功的数据不一致的问题呢?（秒杀成功数 > MQ异步处理订单后的剩余库存数）？

**Comment by a6678696** [comment]
> 你好，请问这个怎么解决超发的问题呢? 秒杀成功之后进入队列,但是队列是异步的,我没有看到进入队列之后处理数据库库存方法(我思路应该是秒杀成功后进入队列,然后MQ异步支付,库存-1)；我没有看到这部分操作,MQ的异步操作数据库会不会产生与前面秒杀成功的数据不一致的问题呢?（秒杀成功数 > MQ异步处理订单后的剩余库存数）？

减库存操作就在进入队列之后，你去看miaosha-rabbitmq模块下的OrderServiceImpl这个类的add方法，在监听队列并处理消息的方法里是看不出的

![image](https://user-images.githubusercontent.com/45851356/164456837-f98939d8-91f2-4e8b-9b51-955edb6fbf72.png)

在减库存的SQL语句中，判断库存是否大于0，大于0才减库存，所以不会出现秒杀商品库存小于0的情况

![image](https://user-images.githubusercontent.com/45851356/164458641-152c82ad-c2aa-4940-9021-f9ef446dfd98.png)

秒杀流程图如下：

![1](https://user-images.githubusercontent.com/45851356/164458830-a15258d2-5e3d-4097-93dc-325645b7a882.png)

**Comment by pchSir** [comment]
你好，这里是不是还有一个问题, 秒杀成功后加入订单，是不是应该有一个支付时间的问题(一般30分钟)，我抢到了这个订单(假设支付时间为30分钟), 但是在规定的时间内我没有支付,这个订单最后应该是无效了的, 商品回滚回数据库,数据库商品+1 ？ 这部分的操作好像我没有看到在哪里实现。

**Comment by ytc0418** [comment]
> 单体架构

感谢大佬！！！我用的是单体架构，是application.yml这里我需要怎么配置，配置本机的是吗？
 rabbitmq:
    host: 192.168.0.141
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: CORRELATED
    virtual-host: /

**Comment by ytc0418** [comment]
> 单体架构

感谢大佬！！！我用的是单体架构，是application.yml这里我需要怎么配置，配置本机的是吗？
 rabbitmq:
    host: 192.168.0.141
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: CORRELATED
    virtual-host: /

**Comment by pchSir** [comment]
抽空把超时支付整上去啊, 我也在拿你项目学习,这个超时支付这个功能还是很重要的,这样这个项目才能实现一个功能上的闭环。我觉得这个要增加一个支付订单的接口,还要在miaoShaGoods添加的支付过期时间字段, 进入支付订单接口以后拿orderId去查询数据, 查看支付过期时间,过期的话删除Redis 给 key ，跟miaoShaGoodsList 里面对应的商品, 然后这个商品数据回滚数据库,再一次加入秒杀活动里面。(具体怎么实现同学你来写啊, PS： 你的代码)

**Comment by a6678696** [comment]
> @ytc0418
> > 单体架构
> 
> 感谢大佬！！！我用的是单体架构，是application.yml这里我需要怎么配置，配置本机的是吗？
>  rabbitmq:
>     host: 192.168.0.141
>     port: 5672
>     username: admin
>     password: admin
>     publisher-confirm-type: CORRELATED
>     virtual-host: /

建议在虚拟机内使用Docker安装RabbitMQ吧（我的Linux系统是CentOS7），`192.168.0.141`这个就是虚拟机的IP地址，如果已经在本机安装了，应该是改成`127.0.0.1`，能在虚拟机安装的就尽量不要在本机安装了

CentOS7安装Docker，查看博客：https://blog.zoutl.cn/290.html

Docker安装RabbitMQ，查看博客：https://blog.zoutl.cn/340.html

**Comment by a6678696** [comment]
> @pchSir
> 抽空把超时支付整上去啊, 我也在拿你项目学习,这个超时支付这个功能还是很重要的,这样这个项目才能实现一个功能上的闭环。我觉得这个要增加一个支付订单的接口,还要在miaoShaGoods添加的支付过期时间字段, 进入支付订单接口以后拿orderId去查询数据, 查看支付过期时间,过期的话删除Redis 给 key ，跟miaoShaGoodsList 里面对应的商品, 然后这个商品数据回滚数据库,再一次加入秒杀活动里面。(具体怎么实现同学你来写啊, PS： 你的代码)

已经搞定，代码重新push到GitHub了

**Comment by pchSir** [comment]
//判断用户是否重复秒杀,已经秒杀过不能秒杀,即使订单因为30分钟未支付被取消了也不能重新秒杀
                if (orderService.findByUserIdAndMiaoShaGoodsId(map) == null) {
                    Order order = new Order();
                    order.setGoodsId(orderVo.getGoodsId());
                    order.setUserId(orderVo.getUserId());
                    order.setPrice(orderVo.getPrice());
                    order.setMiaoShaGoodsId(orderVo.getMiaoShaGoodsId());
                    order.setPayStatus(0);
                    order.setNum(1);
                    orderService.add(order);
                }

//即使订单因为30分钟未支付被取消了也不能重新秒杀 (这样设计是不是不友好?)

假设有这样的一个场景： 
美少女参加抢LV包活动,抢到了一激动苹果手机掉地上开不了机,这时候需要电脑登录完成支付,等美少女登录上去已经过了支付时间(30分钟)，这个LV包跟美少女无缘了,但是抢LV包活动还在继续,她应该还可以继续参加活动。

**Comment by a6678696** [comment]
> @pchSir
> ```java
> //判断用户是否重复秒杀,已经秒杀过不能秒杀,即使订单因为30分钟未支付被取消了也不能重新秒杀
> if (orderService.findByUserIdAndMiaoShaGoodsId(map) == null) {
> 	Order order = new Order();
> 	order.setGoodsId(orderVo.getGoodsId());
> 	order.setUserId(orderVo.getUserId());
> 	order.setPrice(orderVo.getPrice());
> 	order.setMiaoShaGoodsId(orderVo.getMiaoShaGoodsId());
> 	order.setPayStatus(0);
> 	order.setNum(1);
> 	orderService.add(order);
> }
> ```
> 
> //即使订单因为30分钟未支付被取消了也不能重新秒杀 (这样设计是不是不友好?)
> 
> 假设有这样的一个场景： 
> 美少女参加抢LV包活动,抢到了一激动苹果手机掉地上开不了机,这时候需要电脑登录完成支付,等美少女登录上去已经过了支付时间(30分钟)，这个LV包跟美少女无缘了,但是抢LV包活动还在继续,她应该还可以继续参加活动。
> 
> 

我改的话要修改两个项目的，麻烦，我就不改了，其实我在完成秒杀功能时就觉得差不多了，这个系统的重点就是秒杀这个功能，其它功能的细节太多改起来也烦，你在意的话可以自己改一改

**Comment by qingsen1** [comment]
请问引用的其他yml配置可以在哪看见了

**Comment by a6678696** [comment]
> 请问引用的其他yml配置可以在哪看见了

在file文件夹里面，在Nacos中导入，也可以解压后查看

![image](https://user-images.githubusercontent.com/45851356/167074213-8d10d3ae-17f5-41ae-a94f-1d72b461bb0c.png)

**Comment by qingsen1** [comment]
![image](https://user-images.githubusercontent.com/82099168/167078779-1ed9bbfe-60f0-4adb-a438-6e5496572824.png)
![image](https://user-images.githubusercontent.com/82099168/167078874-46e3db54-0b55-4feb-a25f-2577042fbcf5.png)
![image](https://user-images.githubusercontent.com/82099168/167078912-d8facec8-36a1-4622-8bd2-365d471bd075.png)
大佬，明明已经在配置文件中修改了nacos的ip，我在启动服务时为什么还是在本地localhost中寻找，然后报无法连接的错误，麻烦大佬给我看一下。

**Comment by a6678696** [comment]
> @qingsen1
> ![image](https://user-images.githubusercontent.com/82099168/167078779-1ed9bbfe-60f0-4adb-a438-6e5496572824.png)
> ![image](https://user-images.githubusercontent.com/82099168/167078874-46e3db54-0b55-4feb-a25f-2577042fbcf5.png)
> ![image](https://user-images.githubusercontent.com/82099168/167078912-d8facec8-36a1-4622-8bd2-365d471bd075.png)
> 大佬，明明已经在配置文件中修改了nacos的ip，我在启动服务时为什么还是在本地localhost中寻找，然后报无法连接的错误，麻烦大佬给我看一下。
> 
你去看看你的Nacos配置文件所在命名空间id是什么，应该是和我的不一样吧，你现在用的是我的

**Comment by lilycy0580** [comment]
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN.   springcloud 微服务架构 所有微服务启动都ok 就是rabbitmq启动报错 添加新的用户guest123赋权admin ， virtual-host只有 /  更改guest权限为admin  同时在naocs配置文件中分别使用guest与guest123，更改ip地址为localhost,127.0.0.1，本机ip均不行，大佬有可行的解决方案么 谢谢啦  卡了7 8 个小时了   偷偷说一句 大佬的项目跑起来真舒服 0bug

**Comment by a6678696** [comment]
> com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. springcloud 微服务架构 所有微服务启动都ok 就是rabbitmq启动报错 添加新的用户guest123赋权admin ， virtual-host只有 / 更改guest权限为admin 同时在naocs配置文件中分别使用guest与guest123，更改ip地址为localhost,127.0.0.1，本机ip均不行，大佬有可行的解决方案么 谢谢啦 卡了7 8 个小时了 偷偷说一句 大佬的项目跑起来真舒服 0bug

* 我的RabbitMQ（用Docker安装，[查看安装教程](https://blog.zoutl.cn/340.html)）和Nacos环境（[查看安装教程](https://blog.zoutl.cn/472.html)）都是安装在虚拟机的Linux系统中的（云服务器的也试过，都是一样的），所以项目要配置的地址是虚拟机的IP，RabbitMQ使用默认的admin账号，这个项目一般安装好环境以及在Java的配置中设置好就可以的了，我没出现什么问题
* 如果你的环境是直接安装在自己的电脑上的话，项目配置的地址就是localhost或者127.0.0.1，而不是你的IP地址

**Comment by vincent434421** [comment]
给大家排个坑, 这里消息队列是需要延迟队列插件的, 不然这个微服务启不来. 我折腾了一下午
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.8.9

**Comment by a6678696** [comment]
> @vincent434421
> 给大家排个坑, 这里消息队列是需要延迟队列插件的, 不然这个微服务启不来. 我折腾了一下午
> https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.8.9

谢谢你的提醒，安装延迟队列插件的过程可查看博客：https://blog.zoutl.cn/356.html

**Comment by 6greenhand** [comment]
大佬有接口文档吗

**Comment by a6678696** [comment]
> 大佬有接口文档吗

没有
